### ISSUE TITLE
How is model trained and what is the map?

### ISSUE THREAD

**Issue by elmbrahim** [KelvinPuyam/Real-time-object-detection#8]
I want to know if mobilenet_v3 can be trained with a custom dataset. If so, which tensorflow is used? Also, what are the latency and map of the model?

Thank you in advance

**Comment by KelvinPuyam** [comment]
Yes, ssd mobilenet_v3 can be trained with a custom dataset. Generally Tensorflow versions above 2 are used for training. On modern hardware, such as an NVIDIA Tesla V100 GPU, the latency can be as low as 20-30 milliseconds per frame. The model achieves a map of around 22% to 23% on the COCO dataset.
